- name: Update Api
  hosts: all
  vars:
    date: '{{ lookup(''pipe'', ''date +"%Y%m%d"'') }}'
    gitlab_user: 'aoer%40qq.com'
    gitlab_pwd: 'a123456789'
  tasks:
    - name: update service
      block:

        - name: 同步目录
          win_robocopy:
            src: C:\App\XB5_Payment
            dest: C:\PaymentBackup\webapp{{date}}
            flags: /E
        
        - name: 如果目錄不存在,拉取publish_general
          win_shell: git clone http://{{gitlab_user}}:{{gitlab_pwd}}@gitlab.noyasoft.com/operationGroup//publish_general.git
          args:
            chdir: C:\Git
            creates: C:\Git\publish_general

        - name: 更新publish_general
          win_shell: git pull http://{{gitlab_user}}:{{gitlab_pwd}}@gitlab.noyasoft.com/operationGroup/publish_general.git
          args:
            chdir: C:\Git\publish_general
        
        - name: 暂停web服务
          win_shell: |
            C:\Windows\System32\inetsrv\appcmd stop apppool /apppool.name: XB5_Api01
            C:\Windows\System32\inetsrv\appcmd stop sites XB5_Api01
        
        # - name: 䨱盖web目录，排除Config, 排除档案Web.config
        #   win_robocopy:
        #     src: C:\Git\publish_xb3_xb5_n6\(4)webApp-v1.3.72hotfix2\LotteryWeb
        #     dest: C:\App\XB5_Api01\
        #     flags: /E /PURGE /XD Config /XF Web.config

        # - name: 啓动web服务
        #   win_shell: |
        #     C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name: XB5_Api01
        #     C:\Windows\System32\inetsrv\appcmd start sites XB5_Api01

        - name: 发送通知
          import_tasks: telegram.yml
          vars:
            msg: "all tasks finished"
      rescue:
        - debug:
            msg: "revert from backup"
        - win_robocopy:
            dest: C:\App\XB5_Api01
            src: C:\AppBackup\webapp{{date}}
        - win_shell: |
            C:\Windows\System32\inetsrv\appcmd start apppool /apppool.name: XB5_Api01
            C:\Windows\System32\inetsrv\appcmd start sites XB5_Api01
        - debug:
            msg:
              - "{'name': {{ ansible_failed_task.name }}, 'msg': {{ ansible_failed_result.stderr }}}"
        - import_tasks: telegram.yml
          vars:
            msg: "error"
            # msg: "'name': {{ ansible_failed_task.name }}, 'msg': {{ ansible_failed_result.stderr }}"
